---
parameters:
  - name: service_connection
    default: rdp03-ansible-agent-ssh-service-connection
  - name: pipeline
  - name: playbook

jobs:
  - job: "molecule_test"
    displayName: "end to end testing"
    pool: "Azure Self-Hosted"
    steps:
      - task: SSH@0
        displayName: "molecule test"
        inputs:
          sshEndpoint: ${{ parameters.service_connection }}
          runOptions: "inline"
          inline: |
            export VMWARE_VSPHERE_USER=$(VMWARE_VSPHERE_USER)
            export VMWARE_VSPHERE_PASSWORD=$(VMWARE_VSPHERE_PASSWORD)
            export PY_COLOR="1"
            
            cd azure_pipelines/${{ parameters.pipeline }}
            molecule test
          readyTimeout: "20000"
