---
parameters:
  - name: service_connection
    default: rdp03-ansible-agent-ssh-service-connection
  - name: pipeline
  - name: playbook

jobs:
  - job: "molecule_test"
    displayName: "full end to end testing"
    pool: "Azure Self-Hosted"
    steps:
      - task: SSH@0
        env:
          PY_COLOR: "1"
        displayName: "molecule test"
        inputs:
          sshEndpoint: ${{ parameters.service_connection }}
          runOptions: "inline"
          inline: |
            cd azure_pipelines/${{ parameters.pipeline }}
            molecule test
          readyTimeout: "20000"
