---
parameters:
  - name: service_connection
    default: rdp03-ansible-agent-ssh-service-connection
  - name: pipeline

jobs:
  - job:
    steps:
    - bash: echo $VMWARE_VSPHERE_USER
  - job: "files"
    displayName: "copy files to ACS"
    pool: "Azure Self-Hosted"
    steps:
      - task: CopyFilesOverSSH@0
        displayName: "copying"
        inputs:
          sshEndpoint: ${{ parameters.service_connection }}
          contents: "**"
          targetFolder: "azure_pipelines/${{ parameters.pipeline }}"
          readyTimeout: "20000"
          cleanTargetFolder: true
          failOnEmptySource: true
  - job: "environment"
    displayName: "create environment"
    pool: "Azure Self-Hosted"
    dependsOn: "files"
    steps:
      - task: SSH@0
        env:
          TEST_VAR: ${VMWARE_VSPHERE_USER}
          TEST_VAR1: $(VMWARE_VSPHERE_USER)
          TEST_VAR2: "1"
        displayName: "create virtual environment"
        inputs:
          sshEndpoint: ${{ parameters.service_connection }}
          runOptions: "inline"
          inline: |
            env
            pyenv virtualenvs --bare | grep ${{ parameters.pipeline }} && pyenv virtualenv-delete -f ${{ parameters.pipeline }}
            pyenv virtualenv -f ${{ parameters.pipeline }}
            cd azure_pipelines/${{ parameters.pipeline }}
            pyenv local ${{ parameters.pipeline }}
          readyTimeout: "20000"
  - job: "dependencies"
    displayName: "installing dependencies"
    pool: "Azure Self-Hosted"
    dependsOn: "environment"
    steps:
      - task: SSH@0
        continueOnError: true
        displayName: "install requirements"
        inputs:
          sshEndpoint: ${{ parameters.service_connection }}
          runOptions: "inline"
          inline: |
            cd azure_pipelines/${{ parameters.pipeline }}
            pip install --no-warn-script-location --disable-pip-version-check -r requirements.txt
            ansible-galaxy collection install -r collection.yml
          readyTimeout: "20000"
