parameters:
  - name: service_connection
    default: rdp03-ansible-agent-ssh-service-connection
  - name: pipeline
  - name: playbook

jobs:
  - job: "syntax_check"
    displayName: "syntax checks"
    pool: "Azure Self-Hosted"
    steps:
      - task: SSH@0
        displayName: "syntax check"
        inputs:
          sshEndpoint: ${{ parameters.service_connection }}
          runOptions: "inline"
          inline: |
            cd azure_pipelines/${{ parameters.pipeline }}
            ansible-playbook --syntax-check ${{ parameters.playbook }}.yaml
          readyTimeout: "20000"
  - job: "lint"
    displayName: "linting"
    pool: "Azure Self-Hosted"
    steps:
      - task: SSH@0
        displayName: "linter"
        inputs:
          sshEndpoint: ${{ parameters.service_connection }}
          runOptions: "inline"
          inline: |
            echo "hello, world! from molecule test"
          readyTimeout: "20000"