---
- hosts: all
  collections:
    - arnoldclark.rails_applications
  remote_user: root
  vars:
    shared_var_constant_example: 1
  tasks:
    - name: acdotcom
      vars:
        application: acdotcom
        server: unicorn
        workers: 2
        delayed_job_workers: 2
        environment: production
        template: primary_web_servers
      block:
        - name: Configure nginx
          import_role:
            name: rails-applications-nginx-configs
        - name: Configure nginx for rails application
          import_role:
            name: rails-applications-nginx-application-configs
        - name: Configure firewalld for rails applications
          import_role:
            name: rails-applications-firewalld
        - name: Configure the linux server environment for rails applications
          import_role:
            name: rails-applications-environment
        - name: Configure logrotate for rails applications
          import_role:
            name: rails-applications-logrotate
        - name: Configure selinux for rails applications
          import_role:
            name: rails-applications-selinux
      tags: ["acdotcom"]

    - name: gearbox
      vars:
        application: gearbox
        server: unicorn
        environment: production
        template: primary_web_servers
      block:
        - name: Configure nginx
          import_role:
            name: rails-applications-nginx-configs
        - name: Configure nginx for rails application
          import_role:
            name: rails-applications-nginx-application-configs
        - name: Configure firewalld for rails applications
          import_role:
            name: rails-applications-firewalld
        - name: Configure the linux server environment for rails applications
          import_role:
            name: rails-applications-environment
        - name: Configure logrotate for rails applications
          import_role:
            name: rails-applications-logrotate
        - name: Configure selinux for rails applications
          import_role:
            name: rails-applications-selinux
      tags: ["gearbox"]
