---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "*"
pr:
  branches:
    include:
      - main
  paths:
    include:
      - "*"

pool:
  vmImage: "ubuntu-18.04"

variables:
  pipeline: ansible-node-test
  playbook: nginx-configs

stages:
  - stage: "ansible_runtime_environ"
    displayName: "prepare_environ"
    jobs:
      - template: pipeline-templates/ansible_runtime_environ.yaml
        parameters:
          pipeline: $(pipeline)

  - stage: "ansible_runtime_testing"
    displayName: "molecule_test"
    jobs:
      - template: pipeline-templates/ansible_runtime_testing.yaml
        parameters:
          pipeline: $(pipeline)
          playbook: $(playbook)

  - stage: "ansible_runtime_checking"
    displayName: "check_mode"
    jobs:
      - template: pipeline-templates/ansible_runtime_checking.yaml
        parameters:
          pipeline: $(pipeline)
          playbook: $(playbook)
          tags: "gearbox,acdotcom"
          hosts: "iweb2.arnoldclark.com"

  - stage: "ansible_runtime_provisioning"
    displayName: "applying_changes"
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    jobs:
      - template: pipeline-templates/ansible_runtime_provisioning.yaml
        parameters:
          pipeline: $(pipeline)
          playbook: $(playbook)
          tags: "gearbox,acdotcom"
          hosts: "iweb2.arnoldclark.com,iweb3.arnoldclark.com"
