trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "*"
pr:
  branches:
    include: 
      - main
  paths:
    include:
      - "*"

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: "ansible_runtime"
    displayName: "ansible runtime provisioning"

    jobs:
      - job: "test"
        displayName: "ansible-test"
        steps:
          - task: Bash@3
            displayName: "molecule test"
            inputs:
              targetType: "inline"
              script: |
                echo "hello, world! from molecule test"

      - job: "check"
        displayName: "ansible-check"
        steps:
          - task: Bash@3
            displayName: "ansible-playbook"
            inputs:
              targetType: "inline"
              script: |
                echo "hello, world! from ansible-check"
 
      - job: "deploy"
        displayName: "ansible-playbook"
        steps:
          - task: Bash@3
            displayName: "ansible-playbook"
            inputs:
              targetType: "inline"
              script: |
                echo "hello, world! from ansible-playbook"

