trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "*"
pr:
  branches:
    include: 
      - main
  paths:
    include:
      - "*"

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: "ansible runtime testing"
    displayName: "static-analysis"
    jobs:
      - job: "linting"
        displayName: "lint and syntax check"
        steps:
          - task: Bash@3
            displayName: "molecule"
            inputs:
              targetType: "inline"
              script: |
                echo "hello, world! from molecule test"

  - stage: "ansible runtime checking"
    displayName: "check-mode dry-run"
    jobs:
      - job: "checking"
        displayName: "ansible-playbook --check"
        pool: "Azure Self-Hosted"
        steps:
          - task: Ansible@0
            inputs:
              ansibleInterface: "remoteMachine"
              connectionOverSsh: "rdp03-ansible-agent-ssh-service-connection"
              playbookSourceRemoteMachine: "agentMachine"
              playbookRootRemoteMachine: "$(System.DefaultWorkingDirectory)"
              playbookPathLinkedArtifactOnRemoteMachine: "nginx-configs.yaml"
              inventoriesRemoteMachine: "file"
              inventoryFileSourceRemoteMachine: "agentMachine"
              inventoryFileLinkedArtifactOnRemoteMachine: "dev/inventory"
              args: "-CD --tags gearbox --limit iweb2.arnoldclark.com"

  - stage: "ansible runtime provisioning"
    displayName: "applying changes"
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - job: "deploying"
        displayName: "ansible-playbook"
        pool: "Azure Self-Hosted"
        steps:
          - task: Bash@3
            displayName: "ansible-playbook"
            inputs:
              targetType: "inline"
              script: |
                echo "hello, world! from ansible-playbook"