trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "*"
pr:
  branches:
    include: 
      - main
  paths:
    include:
      - "*"

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: "ansible_runtime"
    displayName: "ansible runtime provisioning"
    jobs:
      - job: "ansible_playbook"
        displayName: "ansible-playbook"
        steps:
          - task: Bash@3
            displayName: "Test bash@3 echo"
            inputs:
              script: |
                echo "hello, world!"

