---
- name: Create web root directories
  file:
    path: "{{ webapps_root }}/{{ item.name }}"
    state: directory
    owner: "{{ app_account_username }}"
    group: "{{ app_account_username }}"
    setype: etc_runtime_t
    mode: 0755
  with_items:
    - "{{ rails_applications }}"

- name: Create directory structure per app
  file:
    path: "{{ webapps_root }}/{{ item[0].name }}/{{ item[1] }}"
    state: directory
    owner: "{{ app_account_username }}"
    group: "{{ app_account_username }}"
    mode: 0755
  with_nested:
    - "{{ rails_applications }}"
    - "{{ app_required_directories }}"

- name: Create log directory links
  file:
    src: "{{ webapps_root }}/{{ item.name }}/shared/log"
    dest: "/var/log/{{ item.name }}"
    state: link
    force: yes
  check_mode: no
  with_items:
    - "{{ rails_applications }}"
