---
- name: Check for installed firewall
  shell: "set -e -o pipefail && yum list installed | grep firewalld"
  failed_when: False
  changed_when: False
  register: firewalld_present
- import_tasks: package-dependencies.yml
- import_tasks: app-directories.yml

- name: setup nginx server and application directory tree
  block:
  - import_tasks: setup-nginx-directory-tree.yml
    notify: "restart-nginx"
  - import_tasks: nginx-conf-file.yml
    notify: "restart-nginx"
  tags: ["nginx"]

- name: nginx config files for primary_web_servers by application
  block:
  - import_tasks: "primary_web_servers/acdotcom.yml"
    notify: "restart-nginx"
    tags: ["acdotcom", "all_rails_applications"]
  - import_tasks: "primary_web_servers/gearbox.yml"
    notify: "restart-nginx"
    tags: ["gearbox", "all_rails_applications"]
  when: groups["primary_web_servers"] is defined and inventory_hostname in groups["primary_web_servers"]

- name: nginx config files for secondary_web_servers by application
  block:
  - import_tasks: "secondary_web_servers/default-server.yml"
    notify: "restart-nginx"
    tags: ["default", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/abyc.yml"
    notify: "restart-nginx"
    tags: ["abyc", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/acdesign.yml"
    notify: "restart-nginx"
    tags: ["acdesign", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/ace_news.yml"
    notify: "restart-nginx"
    tags: ["ace_news", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/autoparts.yml"
    notify: "restart-nginx"
    tags: ["autoparts", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/branch-manager.yml"
    notify: "restart-nginx"
    tags: ["branch-manager", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/careers.yml"
    notify: "restart-nginx"
    tags: ["careers", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/gearbox_rental.yml"
    notify: "restart-nginx"
    tags: ["gearbox_rental", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/harry_fairbairn.yml"
    notify: "restart-nginx"
    tags: ["harry_fairbairn", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/midwestmotorfactors.yml"
    notify: "restart-nginx"
    tags: ["midwestmotorfactors", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/newsroom.yml"
    notify: "restart-nginx"
    tags: ["newsroom", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/pch-affinity.yml"
    notify: "restart-nginx"
    tags: ["pch-affinity", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/reservations.yml"
    notify: "restart-nginx"
    tags: ["reservations", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/the_hub.yml"
    notify: "restart-nginx"
    tags: ["the_hub", "all_rails_applications"]
  - import_tasks: "secondary_web_servers/video.yml"
    notify: "restart-nginx"
    tags: ["video", "all_rails_applications"]
  when: groups["secondary_web_servers"] is defined and inventory_hostname in groups["secondary_web_servers"]

- name: nginx config files for tertiary_web_servers by application
  block:
  - import_tasks: "tertiary_web_servers/default-server.yml"
    notify: "restart-nginx"
    tags: ["default", "all_rails_applications"]
  - import_tasks: "tertiary_web_servers/gearbox_assure.yml"
    notify: "restart-nginx"
    tags: ["gearbox_assure", "all_rails_applications"]
  when: groups["tertiary_web_servers"] is defined and inventory_hostname in groups["tertiary_web_servers"]

- name: nginx config files for quaternary_web_servers by application
  block:
  - import_tasks: "quaternary_web_servers/default-server.yml"
    notify: "restart-nginx"
    tags: ["default", "all_rails_applications"]
  - import_tasks: "quaternary_web_servers/feed-manager.yml"
    notify: "restart-nginx"
    tags: ["feed-manager", "all_rails_applications"]
  - import_tasks: "quaternary_web_servers/roombooking.yml"
    notify: "restart-nginx"
    tags: ["roombooking", "all_rails_applications"]
  - import_tasks: "quaternary_web_servers/pressr.yml"
    notify: "restart-nginx"
    tags: ["pressr", "all_rails_applications"]
  when: groups["quaternary_web_servers"] is defined and inventory_hostname in groups["quaternary_web_servers"]

- import_tasks: app-server.yml
- import_tasks: open-firewall-ports.yml
  when:
    - not ansible_check_mode
    - firewalld_present.rc == 0
- import_tasks: selinux.yml
- name: Flush handlers
  meta: flush_handlers
