---
- name: Install nginx repo files
  template:
    src: nginx.repo
    dest: /etc/yum.repos.d/
    mode: 0644
  when: ansible_distribution == 'CentOS'

- name: Install nginx package
  yum:
    name: nginx
    state: present

- name: Create the nginx log directory
  file:
    path: /var/log/nginx
    state: directory
    owner: deploy
    group: deploy
    mode: 0755