---
- name: Check for installed firewall
  shell: "set -e -o pipefail && yum list installed | grep firewalld"
  failed_when: False
  changed_when: False
  register: firewalld_present
- import_tasks: package-dependencies.yml

- name: Create directory structure for webapp deployments
  block:
    - name: acdotcom
      import_tasks: filesystem.yml
      import_tasks: application-server.yml
      vars:
        application: acdotcom
        server: unicorn
        workers: 2
        delayed_job_workers: 2
        environment: production
      tags: ["acdotcom"]
    - name: gearbox
      import_tasks: filesystem.yml
      import_tasks: application-server.yml
      vars:
        application: gearbox
        server: unicorn
        environment: production
      vars:
        application: gearbox
      tags: ["gearbox"]
  when: groups["iwebs"] is defined and inventory_hostname in groups["iwebs"]

- name: Create directory structure for webapp deployments
  block:
    - name: acdotcom
      import_tasks: filesystem.yml
      vars:
        application: acdotcom
        server: unicorn
        workers: 2
        delayed_job_workers: 2
        environment: production
      tags: ["acdotcom"]
    - name: gearbox
      import_tasks: filesystem.yml
      vars:
        application: gearbox
        server: unicorn
        environment: production
      tags: ["gearbox"]
  when: groups["primary_web_servers"] is defined and inventory_hostname in groups["primary_web_servers"]

- import_tasks: open-firewall-ports.yml
  when:
    - not ansible_check_mode
    - firewalld_present.rc == 0

- name: Flush handlers
  meta: flush_handlers
