---
- name: Converge
  hosts: all
  tasks:
    - name: "performing setup tasks"
      debug:
        msg: "yolo!"
    - name: "importing playbook"
      import_playbook: 
        name: "../nginx-configs.yaml"