---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: molecule_instance_config
      debug:
        msg: "{{ molecule_instance_config }}"
    - name: destroy <uuid>
      community.general.terraform:
        project_path: "$HOME/ac/ansible-node-test/terraform/vms"
        state: absent
      environment:
        VSPHERE_PASSWORD: "{{ lookup('env', 'VSPHERE_PASSWORD') }}"
        VSPHERE_USER: "e0055059"
