---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Get vm uuid from terraform output
      command: terraform output -json
      args:
        chdir: ../../terraform/vms
      changed_when: false
      register: tf_outputs
    - name: Convert tf output stdout to json
      set_fact:
        server: "{{ tf_outputs.stdout | from_json }}"
    - name: Destroying vm clone instance_name {{ server.instance_name.value }}
      community.general.terraform:
        project_path: "$HOME/ac/ansible-node-test/terraform/vms"
        state: absent
      environment:
        VSPHERE_PASSWORD: "{{ molecule_yml.driver.vmware_vsphere_password }}"
        VSPHERE_USER: "{{ molecule_yml.driver.vmware_vsphere_user }}"