---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Ensure account view is set to DPD
      command: az account set -s DPD
      changed_when: false
    - name: Get Azure Storage Account access key
      command: az storage account keys list -g "terraform-remote-state" -n "actfstate" --subscription "DPD" --query "[0].value" --output tsv
      changed_when: false
      register: access_key
    - name: Perform terraform init so that outputs can be extracted
      command: "terraform init -backend-config=access_key={{ access_key.stdout }} -upgrade=true"
      args:
        chdir: ../../terraform/azure-pipeline-created-iweb-instance
      changed_when: false
    - name: Get vm uuid from terraform output
      command: terraform output -json
      args:
        chdir: ../../terraform/azure-pipeline-created-iweb-instance
      changed_when: false
      register: tf_outputs
    - name: Convert tf output stdout to json
      set_fact:
        server: "{{ tf_outputs.stdout | from_json }}"
    - when: server
      name: Destroying vm clone instance_name {{ server.instance_name.value | default("(no vm to destroy)") }}
      community.general.terraform:
        project_path: "$HOME/azure_pipelines/ansible-node-test/terraform/azure-pipeline-created-iweb-instance"
        state: absent
        force_init: true
        backend_config:
          access_key: "{{ access_key.stdout }}"
      environment:
        VSPHERE_PASSWORD: "{{ molecule_yml.driver.vmware_vsphere_password }}"
        VSPHERE_USER: "{{ molecule_yml.driver.vmware_vsphere_user }}"
