---
dependency:
  name: galaxy
driver:
  name: delegated
  # vsphere_user: e0055059
  # vsphere_password: "{{ lookup('env', 'VSPHERE_PASSWORD') }}"
lint: |
  set -e
  yamllint .
  ansible-lint
syntax: |
  set -e
  ansible-playbook --syntax-check
# platforms.name is used in combination with instance_config_dict to dynamically write the inventory file.
platforms:
  - name: azure-pipeline-created-iweb-instance
provisioner:
  name: ansible
verifier:
  name: ansible
