---
dependency:
  name: galaxy
driver:
  name: delegated
  # vsphere_user: e0055059
  # vsphere_password: "{{ lookup('env', 'VSPHERE_PASSWORD') }}"
lint: |
  set -e
  yamllint .
  ansible-lint
syntax: |
    ansible-playbook --syntax-check
platforms:
  - name: instance
provisioner:
  name: ansible
verifier:
  name: ansible
