---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-playbook --syntax-check
platforms:
  - name: instance
provisioner:
  name: ansible
verifier:
  name: ansible
