---
dependency:
  name: galaxy
  options:
    requirements-file: collections.yml
# other constants can be set on this object
driver:
  name: delegated
  vm_to_clone: iweb2.arnoldclark.com
  vmware_vsphere_user: ${VMWARE_VSPHERE_USER}
  vmware_vsphere_password: ${VMWARE_VSPHERE_PASSWORD}
lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-playbook --syntax-check iwebs.yaml
# platforms.name is used in combination with instance_config_dict to dynamically write the inventory file.
platforms:
  - name: azure-pipeline-created-iweb-instance
    groups:
      - iwebs
    inventory:
      group_vars:
        molecule: true
provisioner:
  name: ansible
  config_options:
    defaults:
      collections_paths: /home/ansible/.ansible/collections/ansible_collections
      stdout_callback: yaml
verifier:
  name: ansible
