---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - block:
        - name: Ensure arnoldclark.com is reachable 
          uri:
            url: http://localhost
            method: GET
            headers:
              Host: arnoldclark.com
            status_code: 200
          register: acdotcom
          
        - assert:
            success_msg: "arnoldclark.com reachable on {{ inventory_hostname }}"
            that: 
              - acdotcom.status == 200
