---
- name: Install web server config files for acdesign
  template:
    src: "server/secondary_web_servers/acdesign.server.conf.j2"
    dest: "/etc/nginx/conf.d/servers/acdesign.server.conf"
    owner: root
    mode: 0644
