- name: Install web app config files for newsroom
  template:
    src: "locations/secondary_web_servers/newsroom.app.conf.j2"
    dest: "/etc/nginx/conf.d/locations/newsroom.app.conf"
    owner: root
    mode: 0644

- name: Install web app upstream files for newsroom
  template:
    src: "upstream/secondary_web_servers/newsroom.upstream.conf.j2"
    dest: "/etc/nginx/conf.d/upstreams/newsroom.upstream.conf"
    owner: root
    mode: 0644