---
- name: Check for installed firewall
  shell: "set -e -o pipefail && yum list installed | grep firewalld"
  failed_when: False
  changed_when: False
  register: firewalld_present
- import_tasks: package-dependencies.yml


- name: Nginx config files for iwebs by application
  block:
    - name: 
      import_tasks: filesystem.yml
      vars:
        applications: ["acdotcom", "gearbox"]
  when: groups["iwebs"] is defined and inventory_hostname in groups["iwebs"]




- import_tasks: app-server.yml
- import_tasks: open-firewall-ports.yml
  when:
    - not ansible_check_mode
    - firewalld_present.rc == 0
- import_tasks: selinux.yml
- name: Flush handlers
  meta: flush_handlers
